const branches = {
0: "Civil Engineering",
1: "Bio Medical Engineering",
2: "Building Engineering and Construction Technology",
3: "Interior Design",
4: "Planning",
5: "Construction Technology & MGT",
6: "MCA(Integrated)",
7: "Mining Engineering",
8: "VLSI Design",
9: "Computer Science(Software Engineering)",
10: "Computer Science and Engineering",
11: "Computer Science and Information Technology",
12: "Computer Science",
13: "Information Technology",
14: "MCA",
15: "Computer Engineering",
16: "CAD CAM",
17: "Mechanical(CAD)",
18: "Advance Computer Aided Design",
19: "Computer (Distributed System)",
20: "Electrical Engineering",
21: "Electrical & Electronics Engineering",
22: "Instrumentation and Control Engineering",
23: "Electrical & Computer Engg.",
24: "Electrical And Electronics(Power Electronics)",
25: "Remote Sensing & GIS",
26: "Computer Integrated Manufacturing",
27: "Digital Communications",
28: "Electrical Engineering(Electrical Power And Energy Systems)",
29: "Electrical(Power System)",
30: "Electronics Engineering",
31: "Electronics and Communication Engineering",
32: "Electronics and Instrumentation Engineering",
33: "Electronics and Telecommunication Engineering",
34:	"Electronics, Instrumentation and Control Engineering",
35:	"Applied Electronics and Instrumentation Engineering",
36:	"Bachelor of Design",
37:	"Electronics Design And Technology",
38:	"Electronics (Control Systems)",
39:	"MBA(Integrated)",
40:	"Mechanical Engineering",
41:	"Manufacturing Technology",
42:	"Manufacturing Science & Technology",
43:	"Mechanical and Industrial Engineering",
44:	"Production Engineering",
45:	"Industrial Production Engineering",
46:	"Production and Industrial Engineering",
47:	"Automobile Engineering",
48:	"Aeronautical Engineering",
49:	"Petroleum Engineering",
50:	"Bachelor of Pharmacy",
51:	"Chemical Engineering",
52:	"Chemical & Bio Engg.",
53:	"Chemical & Alcohol Technology",
54:	"Biotechnology",
55:	"Bio Chemical Engineering",
56:	"Pharmaceutics",
57:	"Pharmceutical Chemistry",
58:	"Pharmacogonosy",
59:	"Marine Engineering",
60:	"Textile Chemistry",
61:	"Textile Technology",
62:	"Man Made Fibre Technology",
63:	"Textile Engineering",
64:	"Carpet & Textile Technology",
65:	"BFAD",
66:	"Bachelor of Fine Art(BFA)",
67:	"Computer science and engineering with specialization in cyber security/ ICT",
68:	"Electronics(Microwave Enginnering)",
69:	"Thermal Engineering",
70:	"MBA",
71:	"MBA in Tourism Management",
72:	"MBA Rural Development",
73:	"Structural Engineering",
74:	"BHMCT",
75:	"Automation and Robotics",
76:	"Power Electronics And Drives",
77:	"Power Systems",
78:	"Machine Design",
79:	"Electronic And Computer Engineering",
80:	"Agricultural Engineering",
81:	"Architecture",
82:	"Food Technology",
83:	"PHARMACEUTICAL REGULATORY AFFAIRS",
84:	"Chemical Technology - Oil Technology",
85:	"Master of Architecutre",
86:	"Leather Technology",
87:	"Plastic Engineering",
88:	"Electrical Drive and Control",
89:	"Information & Communication Technology",
90:	"MBA(International Business)",
91:	"Quality Assurance",
92:	"Computer Network Engg",
93:	"Masters of Applied Mangement",
94:	"MCA Dual Degree",
95:	"Mechatronics",
96:	"Nanotechnology",
97:	"Environmental Engineering",
98:	"Pharmacology",
99:	"PHARMACEUTICAL QUALITY ASSURANCE",
101: "Automotive Manufacturing Technology",
102: "Automobile Servicing",
103: "Production Technology",
104: "Industrial Tool Manufacturing (ITM)",
105: "Refrigeration and Air Conditioning",
106: "Softwaree Development",
107: "Graphics & Mutimedia",
108: "BFSI",
109: "Travel & Tourism",
110: "Food Processing",
111: "Electronic Manufacturing Servicing",
112: "Medical Imaging Technology",
113: "Printing & Packing Technology",
114: "Communication Engineering",
115: "Mobile Communication",
116: "Artificial Intelligence",
117: "Energy Science & Technology",
118: "Fashion Design",
119: "Microelectronics Engineering",
120: "Pharmaceutical Analysis",
121: "Pharmaceutical Analysis And Quality Assurance",
122: "M.Pharma.",
123: "Geotechnical & Geoenvironmental Engineering",
124: "Master of Design",
125: "Advance Electronics & Communication Engineering",
126: "Chemical Technology",
127: "Communication & Information System",
128: "Computer Hardware & Networking",
129: "Computer Engineering And Information Technology",
130: "Master In Urban and Regional Planning",
131: "Computer Science & Technology",
132: "Construction Technology & Management",
133: "Digital Electronics & Commuincation Engineering",
134: "Drug Regulatory",
135: "Electronics Circutis & System Design",
136: "Enviourmentaion Technology",
137: "Machine Design & Industrial System Engineering",
138: "Machine Design & Robotics",
139: "Manufacturing System",
140: "Mechanical & Manufacturing",
141: "Mechanical Engineering Design",
143: "Pharmaceutical",
144: "Telecomm Engineering",
145: "VLSI & Embed System",
146: "Pharmaceutical Marketing MGT.",
147: "MTM",
148: "Ceramic Technology",
149: "Pharma Chemistry",
150: "Chemical Technology - Paint Technology",
151: "Manufacturing Technology and Automation",
152: "Computer Science and Engineering (Artificial Intelligence)",
153: "Computer Science And Engineering(Artificial Intelligence & Machine Learning)",
154: "Computer Science And Engineering(Data Science)",
155: "Computer Science And Engineering(Internet Of Things)",
156: "Computer Science And Business System",
157: "MBA(Business Analytics)",
158: "MBA(Logistics and supply chain management)",
159: "Innovation Entrepreneurship and Venture Devlopement",
160: "Handloom & Textile Technology",
161: "Robotics And Automation",
162: "Environmental Design",
163: "Artificial Inelligence (AI) And Data Science",
164: "Artificial Intelligence And Machine Learning",
165: "Computer Science And Design",
166: "Pharmacy Practice",
167: "Pharm D",
168: "Power and Energy System",
169: "Computer Science (Hindi)"
};

module.exports = branches;