const subjects = {
"KOE031": "Engineering Mechanics",
"KOE032": "Material Science",
"KOE033": "Energy Science & Engineering",
"KOE034": "Sensor & Instrumentation",
"KOE035": "Basics Data Structure & Algorithms",
"KOE036": "Introduction to Soft Computing",
"KOE037": "Analog Electronics Circuits",
"KOE038": "Electronics Engineering","KECZ-501": "Integrated Circuit Design",
"KECZ-502": "Digital Signal Processing",
"KECZ-502": "Database Management System",
"KECZ-051": "Department Elective-I",
"KECZ-055": "Department Elective-II",
"KECZ-551": "Integrated Circuits Lab",
"KECZ-552": "Database Management System Lab", 
"KECZ-553": "Digital Signal Processing Lab",
"KECZ-554": "Mini Project/Internship",
"KNC501":"Constitution",
"KAS302" :"Maths IV",
"KAS301":"Technical Communication",
"KCS301" :"Data Structure",
"KCS302" :"Computer Organization and Architecture",
"KCS303" :"Discrete Structures & Theory of Logic",
"KCS351" :"Data Structures Using C Lab",
"KCS352" :"Computer Organization Lab",
"KCS353" :"Discrete Structure & Logic Lab",
"KCS354" :"Mini Project or Internship Assessment",
"KNC301" :"Computer System Security",
"KAS101T":"Engineering Physics",
"KAS102T":"Engineering Chemistry",
"KAS103T" :"Engineering Mathematics-I",
"KEE101T":"Basic Electrical Engineering",
"KEC101T":"Emerging Domain in Electronics Engineering",
"KCS101T":"Programming for Problem Solving",
"KME101T":"undamentals of Mechanical Engineering & Mechatronics",
"KAS151P":"Engineering Physics Lab",
"KAS152P":"Engineering Chemistry Lab",
"KEE151P":"Basic Electrical Engineering Lab",
"KEC151P":"Electronics Engineering Lab",
"KCS151P":"Programming for Problem Solving",
"KAS154P": "English Language Lab",
"KCE151P":"Engineering Graphics & Design Lab",
"KWS151P":"Mechanical Workshop Lab",
"KMC101":"AI For Engineering",
"KMC102":"Emerging Technology for Engineering",
"KNC101" :"Soft Skill I"
};

module.exports = subjects;